version: "3.9"

services:
  fastapi-app:
    build: .
    restart: always
    container_name: fastapi-container
    ports:
      - "4425:8000"
    volumes:
      - .env:/code/.env
      - ./weights/rus.traineddata:/code/weights/rus.traineddata