version: "3.9"

services:
  fastapi-app:
    build: .
    restart: always
    container_name: fastapi-container
    ports:
      - "4425:7860"
    volumes:
      - .env:/code/.env
      - ./weights:/code/weights
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - TESSDATA_PREFIX=/code/weights/tessdata/